# Generated by Django 5.0.2 on 2024-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
