# Generated by Django 5.0.2 on 2024-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_yourmodel_options_remove_yourmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('film', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
